In [11]:
a = 10
b = 20

In [2]:
c = a + b

In [3]:
print(c)

30


In [4]:
a = 10

In [5]:
a

10

In [9]:
a = "ask"
a

'ask'

In [7]:
a = 2.0
a

2.0

In [12]:
print(a+b)

30


In [13]:
10 + 20

30

In [19]:
a = "10"
b = "ask"

In [20]:
a + b

'10ask'

In [22]:
a = [1,2,3,5,9,0]

In [25]:
a[4]

9

In [29]:
a = ["hammad","titu","sexy"]
b = ["hammad1","titu2","sexy2"]
c = ["hammad3","tit3","sexy3"]

In [27]:
a[0]

'hammad'

In [28]:
a[2]


'sexy'

In [30]:
a[1]
b[1]
c[1]

'tit3'

In [33]:
print(a[1],b[1],c[1])

titu titu2 tit3


In [34]:
a = [1,2,3,5,9,0]

In [36]:
for i in range(6):
    print(a[i])

1
2
3
5
9
0


In [39]:
a = [1,2,3,5,9,0]

In [41]:
for i in range(6):
    print(a[i])

1
2
3
5
9
0


In [43]:
a = [1,2,3,5,9,0]
b = [11,20,30,50,90,10]

In [46]:
for i in range(6):
    
    print(a[i]+b[i])



12
22
33
55
99
10


In [47]:
a = [1,2,3,5,9,0,"hammad"]

In [48]:
a = [1,2,3,5,9,0]

In [52]:
a.sort()
a

[0, 1, 2, 3, 5, 9]

In [2]:
a = [1,2,3,5,9,0]

In [3]:
sum(a)

20

In [4]:
uid = ['hammad','hidie','ssy']

In [5]:
pswd = ['33','444']

In [11]:
p1 = dict(uid='ssy',psd='222')
p2 = dict(uid='hiddie',psd='333')

In [13]:
p1['uid']

'ssy'

In [14]:
p1['psd']

'222'

In [25]:
person1 = dict(name="ssy",addr="uxbridge",income=1000,code='ub670')
person2 = dict(name="tty",addr="reding",income=5000,code='bx670')
person3 = dict(name="swty",addr="sire",income=3000,code='tx670')

In [18]:
person1['name']

'ssy'

In [19]:
person1['addr']

'uxbridge'

In [20]:
person1['addr'] = 'central'

In [21]:
person1

{'name': 'ssy', 'addr': 'central', 'income': 1000, 'code': 'ub670'}

In [22]:
person1 = dict(name="ssy",addr=['central','ub5678'],income=1000)


In [24]:
person1['addr'][0]

'central'

In [26]:
details = [person1,person2,person3]

In [27]:
details

[{'name': 'ssy', 'addr': 'uxbridge', 'income': 1000, 'code': 'ub670'},
 {'name': 'tty', 'addr': 'reding', 'income': 5000, 'code': 'bx670'},
 {'name': 'swty', 'addr': 'sire', 'income': 3000, 'code': 'tx670'}]

In [30]:
for i in range(3):
    print(details[i])

{'name': 'ssy', 'addr': 'uxbridge', 'income': 1000, 'code': 'ub670'}
{'name': 'tty', 'addr': 'reding', 'income': 5000, 'code': 'bx670'}
{'name': 'swty', 'addr': 'sire', 'income': 3000, 'code': 'tx670'}


In [32]:
for i in range(3):
    print(details[i]['name'])
   

ssy
tty
swty


In [35]:
d1 = dict(uid="sty",psd = '22')
d2 = dict(uid="pty",psd = '11')

In [36]:
d1['uid']

'sty'

In [37]:
a = [1,2,3,5,9,0]

In [40]:
a[3] = 0

In [41]:
a

[1, 2, 3, 0, 9, 0]

In [42]:
a = [1,2,3,5,9,0]
b = [11,20,30,50,90,10]

In [43]:
for i in range (6) :
    print (a[i]+b[i])


12
22
33
55
99
10


In [44]:
for i in range (6) :
    print (a[i]*b[i])

11
40
90
250
810
0


In [50]:
a = [1,2,0,5,9,0]
b = [11,20,30,50,90,10]

In [56]:
for i in range (6) :
    if a[i] == 0:
        continue
    else:
        
        print (b[i]/a[i])

11.0
10.0
10.0
10.0


In [54]:
 30 == 10

False

In [57]:
b = [11,20,30,50,90,10]

In [58]:
for i in range (6) :
    print (b[i])

11
20
30
50
90
10


In [60]:
for i in range (6) :
    if b[i]  > 30 :
        print (b[i])
    else:
        print("*")
   
        

*
*
*
50
90
*


In [61]:
b = [11,20,30,50,90,10]

In [62]:
for i in range (6) :
    if b[i]  > 30 :
        print (b[i])
    else:
        b[i]= b[i]+5

50
90


In [63]:
b

[16, 25, 35, 50, 90, 15]

In [64]:
for i in range (6) :
    if b[i]  > 30 :
        print (b[i])
    else:
        b[i]= b[i]*2

35
50
90


In [72]:
b = [11,22,3,5,90,10]

In [68]:
for i in range (6) :
    b[i] = b[i] + 10

In [69]:
b

[21, 30, 40, 60, 100, 20]

In [73]:
for i in range (6) :
    if b[i] % 2 == 0 :
        b[i] = b[i]*2

In [74]:
b

[11, 44, 3, 5, 180, 20]

In [83]:
for i in range(3,9,1):
    print(i)

3
4
5
6
7
8


In [78]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [85]:
a = ['sny','king','tin','sin','min','lastn']

In [86]:
for i in a:
    print(i)

sny
king
tin
sin
min
lastn


In [88]:
l = len(a)
l

6

In [90]:
for i in range(0,l,3):
    print(a[i])

sny
sin


In [91]:
for i in range(0,l,2):
    print(a[i])

sny
tin
min


In [94]:
for i in range(0,101,5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


In [ ]:
a = [2,5,7,8,9,3,5,66,88]

In [95]:
details = ['aramco','sny','logopath']

In [97]:
details[0] = 'mramco'

In [98]:
details

['mramco', 'sny', 'logopath']

In [99]:
details = ('aramco','sny','logopath')

In [100]:
details[0]

'aramco'

In [102]:
details[0]= "ard"

TypeError: 'tuple' object does not support item assignment

In [105]:
details = ('aramco','sny','logopath')
details

('aramco', 'sny', 'logopath')

In [117]:
time = 2

In [119]:

if(time > 2):
    print("after noon")
elif (time<2):
    print("before noon")
else:
    print("no match, timing perfect")

no match, timing perfect


In [121]:
import time
ham =  time.ctime()
print(ham)

Mon Mar 13 20:26:43 2023


In [122]:
def checktime(time):
    if(time > 2):
        print("after noon")
    elif (time<2):
        print("before noon")
    else:
        print("no match, timing perfect")
        


In [123]:
checktime(4)

after noon


In [124]:
checktime(1)

before noon


In [127]:
details = ('hmd','123')
def checkDetails(name,pwd):
    if name == details[0] and pwd == details[1]:
        print("user is proper")
    else:
        print("not proper user")
    
    

In [128]:
checkDetails('sny','123')

not proper user


In [129]:
checkDetails('hmd','123')

user is proper


In [137]:
details = ('hmd','123')
def checkDetails(name="sny",pwd="123"):
    if name == details[0] and pwd == details[1]:
        print("user is proper")
    else:
        print(name,pwd)
        print("not proper user")

In [133]:
checkDetails(name="tt",pwd='123')

not proper user


In [134]:
checkDetails("tt",'123')

not proper user


In [135]:
checkDetails(pwd='123',name='hmd')

user is proper


In [138]:
checkDetails()

sny 123
not proper user


In [143]:
a = [11,20,30,50,90,10]
def display():
    for i in range(6):
        print (a[i])
    


In [145]:

details = ('hmd','123')
def checkDetails(name="sny",pwd="123"):
    if name == details[0] and pwd == details[1]:
        print("user is proper")
        display()
        
    else:
        print(name,pwd)
        print("not proper user")

In [147]:
checkDetails('hm','123')

hm 123
not proper user


In [150]:

def display(array):
    for i in range(6):
        print (array[i])

In [151]:
a = ['sny','king','tin','sin','min','lastn']

In [152]:
display(a)

sny
king
tin
sin
min
lastn


In [155]:
 def mysum(n1,n2):
        a = n1
        b = n2
        print(a+b)
        


In [156]:
mysum(3,5)

8


In [157]:
mysum(123,6584)

6707


In [160]:
def mysub(n1,n2):
        a = n1
        b = n2
        print(a-b)
        

In [161]:
mysub(34,21)

13


In [166]:
def mydiv(n1,n2):
    if n2 == 0:
        print('Div noyt possible')
    else:
        a = n1
        b = n2
        print(a/b)
        

In [163]:
mydiv(32,2)

16.0


In [167]:
mydiv(32,0)

Div noyt possible


In [1]:
mysum(6,2)

NameError: name 'mysum' is not defined

In [7]:
def mysub(n1,n2):
        a = n1
        b = n2
        print(a-b)
        
def mysum(n1,n2):
        a = n1
        b = n2
        print(a+b)
        
def mydiv(n1,n2):
    if n2 == 0:
        print('Div noyt possible')
    else:
        a = n1
        b = n2
        print(a/b)
def mymult(n1,n2):
    print(n1*n2)
    

In [3]:
mymult(2,3)

6


In [4]:
mysum(2,3)

5


In [5]:
mysub(2,3)

-1


In [6]:
mydiv(2,3)

0.6666666666666666


In [1]:
name = input("enter name") 
print("how are you ",name)

enter namesny
how are you  sny


In [54]:
def calculator():
    n1 = int(input("enter first no"))
    n2 = int(input("enter seacond no"))
    op = input("enter operation")
    print(n1,"------",n2)
    print("operation to be done:--",op)
    if op == "sum" or op.__contains__("add") or op.__contains__("sum") or op.__contains__("+"):
        mysum(n1,n2)
    elif op== "mult" or op.__contains__('mul') or op.__contains__('*'):
        mymult(n1,n2)
    elif op== "sub":
        mysub(n1,n2)
    elif op== "div":
        mydiv(n1,n2)
    else:
        print("not proper")
    
    

In [55]:
calculator()

enter first no2
enter seacond no3
enter operationadd
2 ------ 3
operation to be done:-- add
5


In [47]:
x = "multiplication"

In [37]:
x.__contains__("mul")

True

In [48]:
import pandas as pd

In [49]:
data = pd.read_csv("/Users/user/Desktop/python activity/sampledata.csv")

In [50]:
data.head(5)

name  age
0    king   50
1  bling   150
2    cat     2
3   mouse    1
4  batman  199

In [51]:
data['name']

0      king
1    bling 
2      cat 
3     mouse
4    batman
Name: name, dtype: object

In [52]:
for item in data['name']:
    print(item)

king
bling 
cat 
mouse
batman


In [53]:
for item in data['name']:
    if(item == "batman"):
        print("found you")
    else:
        
        print("no batman")

no batman
no batman
no batman
no batman
found you


In [56]:
def myAdd(n1,n2):
        a = n1
        b = n2
        print(a+b)

In [59]:
def myAdd(n1,n2,n3):
    print(n1+n2+n3)
        

In [61]:
def myAdd(**kwargs):
   x = 

9


In [62]:
def myAdd(n1 =0,n2=0,n3=0,n4=0,n5=0):
    print(n1+n2+n3+n4+n5)

In [63]:
myAdd()

0


In [64]:
myAdd(n1=4,n2=5)

9


In [65]:
myAdd(n1=4,n2=5,n3=7)

16


In [66]:
myAdd(4,5,7)

16


In [68]:
num = 4
for i in range(num):
    input("enter number")

enter number3
enter number7
enter number6
enter number7


---------------------------------PANDAS ----------------------

In [69]:
import pandas as pd

In [109]:
df = pd.read_csv("/Users/user/Desktop/python activity/AAPL.csv")

In [74]:
df.head(5)

Date        Open        High         Low       Close   Adj Close  \
0  2022-03-31  177.839996  178.029999  174.399994  174.610001  173.558640   
1  2022-04-01  174.029999  174.880005  171.940002  174.309998  173.260422   
2  2022-04-04  174.570007  178.490005  174.440002  178.440002  177.365570   
3  2022-04-05  177.500000  178.300003  174.419998  175.059998  174.005905   
4  2022-04-06  172.360001  173.630005  170.130005  171.830002  170.795380   

      Volume  
0  103049300  
1   78751300  
2   76468400  
3   73401800  
4   89058800

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       251 non-null    object 
 1   Open       251 non-null    float64
 2   High       251 non-null    float64
 3   Low        251 non-null    float64
 4   Close      251 non-null    float64
 5   Adj Close  251 non-null    float64
 6   Volume     251 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.9+ KB


In [79]:
df.describe()

Open        High         Low       Close   Adj Close  \
count  251.000000  251.000000  251.000000  251.000000  251.000000   
mean   149.651435  151.706972  147.745418  149.782231  149.336480   
std     11.327796   11.198026   11.335016   11.251748   11.138808   
min    126.010002  127.769997  124.169998  125.019997  124.829399   
25%    142.110001  143.854996  139.949997  142.464996  141.973427   
50%    148.869995  150.919998  147.240005  149.350006  148.910004   
75%    156.275002  158.154999  154.164993  156.779999  155.852944   
max    177.839996  178.490005  174.440002  178.440002  177.365570   

             Volume  
count  2.510000e+02  
mean   8.148972e+07  
std    2.385313e+07  
min    3.519590e+07  
25%    6.634440e+07  
50%    7.625990e+07  
75%    8.911520e+07  
max    1.826020e+08

In [81]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [82]:
df['Open'].max()

177.839996

In [84]:
df['Adj Close'].min()

124.829399

In [85]:
df['Low'].std()

11.335015828389036

In [87]:
df['Adj Close']

0      173.558640
1      173.260422
2      177.365570
3      174.005905
4      170.795380
          ...    
246    160.250000
247    158.279999
248    157.649994
249    160.770004
250    162.360001
Name: Adj Close, Length: 251, dtype: float64

In [89]:
arr = df['Adj Close'].sort_values()

In [93]:
for i in arr :
    if i > 150:
        print(i)

150.171204
150.221054
150.290833
150.31131
150.470001
150.490234
150.52037
150.589996
150.590088
150.639999
150.839706
150.9086
151.009995
151.029999
151.059357
151.277695
151.366486
151.498688
151.600006
151.6884
151.85585
151.885742
152.252426
152.254578
152.34201
152.550003
152.589996
152.852661
152.869995
152.990005
153.199997
153.231461
153.351074
153.387222
153.710007
153.805298
153.830002
153.850006
153.969116
153.989029
154.038879
154.264465
154.41423
154.641479
154.816406
155.0
155.245056
155.314819
155.330002
155.464355
155.627274
155.82608
155.850006
155.855881
156.074905
156.401352
156.562668
156.63237
156.700745
156.720337
156.869858
157.008896
157.399994
157.457993
157.649994
157.830002
158.279999
158.404984
158.51973
158.929993
159.279999
159.280212
160.25
160.770004
160.773392
160.815796
160.867126
161.768814
161.899261
162.360001
162.654678
162.910599
163.099991
164.07608
164.294739
164.346024
164.395859
164.751968
164.824509
165.02037
165.053772
165.372314
165.417953


In [92]:
df[df['Open']>100]

Date        Open        High         Low       Close   Adj Close  \
0    2022-03-31  177.839996  178.029999  174.399994  174.610001  173.558640   
1    2022-04-01  174.029999  174.880005  171.940002  174.309998  173.260422   
2    2022-04-04  174.570007  178.490005  174.440002  178.440002  177.365570   
3    2022-04-05  177.500000  178.300003  174.419998  175.059998  174.005905   
4    2022-04-06  172.360001  173.630005  170.130005  171.830002  170.795380   
..          ...         ...         ...         ...         ...         ...   
246  2023-03-24  158.860001  160.339996  157.850006  160.250000  160.250000   
247  2023-03-27  159.940002  160.770004  157.869995  158.279999  158.279999   
248  2023-03-28  157.970001  158.490005  155.979996  157.649994  157.649994   
249  2023-03-29  159.369995  161.050003  159.350006  160.770004  160.770004   
250  2023-03-30  161.529999  162.470001  161.270004  162.360001  162.360001   

        Volume  
0    103049300  
1     78751300  
2     76468400  
3     73401800  
4     89058800  
..         ...  
246   59196500  
247   52390300  
248   45992200  
249   51305700  
250   49456700  

[251 rows x 7 columns]

In [95]:
df[(df['Open']>170) & (df['Low']>150)]

Date        Open        High         Low       Close   Adj Close  \
0    2022-03-31  177.839996  178.029999  174.399994  174.610001  173.558640   
1    2022-04-01  174.029999  174.880005  171.940002  174.309998  173.260422   
2    2022-04-04  174.570007  178.490005  174.440002  178.440002  177.365570   
3    2022-04-05  177.500000  178.300003  174.419998  175.059998  174.005905   
4    2022-04-06  172.360001  173.630005  170.130005  171.830002  170.795380   
5    2022-04-07  171.160004  173.360001  169.850006  172.139999  171.103500   
6    2022-04-08  171.779999  171.779999  169.199997  170.089996  169.065857   
10   2022-04-14  170.619995  171.270004  165.039993  165.289993  164.294739   
91   2022-08-11  170.059998  170.990005  168.190002  168.490005  167.954529   
93   2022-08-15  171.520004  173.389999  171.350006  173.190002  172.639587   
94   2022-08-16  172.779999  173.710007  171.660004  173.029999  172.480087   
95   2022-08-17  172.770004  176.149994  172.570007  174.550003  173.995270   
96   2022-08-18  173.750000  174.899994  173.119995  174.149994  173.596527   
97   2022-08-19  173.029999  173.740005  171.309998  171.520004  170.974899   
102  2022-08-26  170.570007  171.050003  163.559998  163.619995  163.099991   

        Volume  
0    103049300  
1     78751300  
2     76468400  
3     73401800  
4     89058800  
5     77594700  
6     76575500  
10    75329400  
91    57149200  
93    54091700  
94    56377100  
95    79542000  
96    62290100  
97    70346300  
102   78961000

In [97]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [99]:
df.shape

(251, 7)

In [102]:
df.drop('Date',axis=1,inplace=True)

In [103]:
df.head()

Open        High         Low       Close   Adj Close     Volume
0  177.839996  178.029999  174.399994  174.610001  173.558640  103049300
1  174.029999  174.880005  171.940002  174.309998  173.260422   78751300
2  174.570007  178.490005  174.440002  178.440002  177.365570   76468400
3  177.500000  178.300003  174.419998  175.059998  174.005905   73401800
4  172.360001  173.630005  170.130005  171.830002  170.795380   89058800

In [105]:
df = df.drop('High',axis=1)

In [106]:
df.head()

Open         Low       Close   Adj Close     Volume
0  177.839996  174.399994  174.610001  173.558640  103049300
1  174.029999  171.940002  174.309998  173.260422   78751300
2  174.570007  174.440002  178.440002  177.365570   76468400
3  177.500000  174.419998  175.059998  174.005905   73401800
4  172.360001  170.130005  171.830002  170.795380   89058800

In [107]:
list_col = ['Open','Low','Close']
df = df.drop(list_col,axis=1)

In [110]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2022-03-31  177.839996  178.029999  174.399994  174.610001  173.558640   
1  2022-04-01  174.029999  174.880005  171.940002  174.309998  173.260422   
2  2022-04-04  174.570007  178.490005  174.440002  178.440002  177.365570   
3  2022-04-05  177.500000  178.300003  174.419998  175.059998  174.005905   
4  2022-04-06  172.360001  173.630005  170.130005  171.830002  170.795380   

      Volume  
0  103049300  
1   78751300  
2   76468400  
3   73401800  
4   89058800

In [112]:
list_col = ['Close','Open']
df = df.drop(list_col,axis=1)

In [117]:
df.head()

Date        High         Low   Adj Close     Volume       value
0  2022-03-31  178.029999  174.399994  173.558640  103049300  356.059998
1  2022-04-01  174.880005  171.940002  173.260422   78751300  349.760010
2  2022-04-04  178.490005  174.440002  177.365570   76468400  356.980010
3  2022-04-05  178.300003  174.419998  174.005905   73401800  356.600006
4  2022-04-06  173.630005  170.130005  170.795380   89058800  347.260010

In [116]:
df["value"] = df['High']*2

In [118]:
df["New"] = df["Low"]*5

In [120]:
df.head()

Date        High         Low   Adj Close     Volume       value  \
0  2022-03-31  178.029999  174.399994  173.558640  103049300  356.059998   
1  2022-04-01  174.880005  171.940002  173.260422   78751300  349.760010   
2  2022-04-04  178.490005  174.440002  177.365570   76468400  356.980010   
3  2022-04-05  178.300003  174.419998  174.005905   73401800  356.600006   
4  2022-04-06  173.630005  170.130005  170.795380   89058800  347.260010   

          New  
0  871.999970  
1  859.700010  
2  872.200010  
3  872.099990  
4  850.650025

In [ ]:
datetime function

# ------------------------------- rev-----------

In [1]:
import numpy as np

In [9]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [12]:
x = np.array([2,5,7,8])
x

array([2, 5, 7, 8])

In [30]:
x = np.arange(60)
y  = x * 0.20
y

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8])

In [31]:
x-y

array([ 0. ,  0.8,  1.6,  2.4,  3.2,  4. ,  4.8,  5.6,  6.4,  7.2,  8. ,
        8.8,  9.6, 10.4, 11.2, 12. , 12.8, 13.6, 14.4, 15.2, 16. , 16.8,
       17.6, 18.4, 19.2, 20. , 20.8, 21.6, 22.4, 23.2, 24. , 24.8, 25.6,
       26.4, 27.2, 28. , 28.8, 29.6, 30.4, 31.2, 32. , 32.8, 33.6, 34.4,
       35.2, 36. , 36.8, 37.6, 38.4, 39.2, 40. , 40.8, 41.6, 42.4, 43.2,
       44. , 44.8, 45.6, 46.4, 47.2])

In [32]:
al = []
for i in range(50):
    al.append(i)

     

In [36]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
y= x*0.5

y

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [39]:
x-y

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [44]:
x = np.linspace(20,100,num = 50)
x

array([ 20.        ,  21.63265306,  23.26530612,  24.89795918,
        26.53061224,  28.16326531,  29.79591837,  31.42857143,
        33.06122449,  34.69387755,  36.32653061,  37.95918367,
        39.59183673,  41.2244898 ,  42.85714286,  44.48979592,
        46.12244898,  47.75510204,  49.3877551 ,  51.02040816,
        52.65306122,  54.28571429,  55.91836735,  57.55102041,
        59.18367347,  60.81632653,  62.44897959,  64.08163265,
        65.71428571,  67.34693878,  68.97959184,  70.6122449 ,
        72.24489796,  73.87755102,  75.51020408,  77.14285714,
        78.7755102 ,  80.40816327,  82.04081633,  83.67346939,
        85.30612245,  86.93877551,  88.57142857,  90.20408163,
        91.83673469,  93.46938776,  95.10204082,  96.73469388,
        98.36734694, 100.        ])

In [46]:
x = np.array([5,3,8,0,9])
x

array([5, 3, 8, 0, 9])

In [48]:
np.sort(x)

array([0, 3, 5, 8, 9])

In [49]:
x= np.array([2,1,6,4,8,9])

In [54]:
y = np.sort(x)

In [53]:
x


array([1, 2, 4, 6, 8, 9])

In [55]:
y

array([1, 2, 4, 6, 8, 9])

In [78]:
x = np.array([[4,6],
              [7,9]])
x

array([[4, 6],
       [7, 9]])

In [79]:
y = np.array([[1,1],
              [1,3]])
y

array([[1, 1],
       [1, 3]])

In [61]:
x*y

array([[ 4,  6],
       [ 7, 27],
       [ 5,  2]])

In [64]:
x = np.array([4,6,7])
x

array([4, 6, 7])

In [65]:
np.sin(x)

array([-0.7568025, -0.2794155,  0.6569866])

In [66]:
x

array([4, 6, 7])

In [80]:
x @ y

array([[10, 22],
       [16, 34]])